# Generated by Django 5.0.1 on 2024-01-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('current_class', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
