# Generated by Django 5.0.1 on 2024-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
